### ISSUE TITLE
Week 4 Individual Review Ticket

### ISSUE THREAD

**Issue by Ritvik-Keerthi** [Ritvik-Keerthi/Ritvik-Keerthi-CSP4#6]
# TOTAL Score: 6/5

# Team Score: 4/3 (already reviewed with extra credit)
# Accounts and Logins

## [Ritvik College Board Create Task](https://ritvik-keerthi.github.io/Ritvik-Keerthi-CSP4/create_task)

- [x] CB Create Task Coding requirements documented
- [x] Runtime of Code(with comments) on Replit/Intellij

### Accounts and Logins Challenges/Hacks ( 3 Points - Team)

- Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
- Analysis: the [csp.nighthawkcodingsociety.com](http://csp.nighthawkcodingsociety.com/) implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.

- [x] Hack#1 Add Phone Number to Sign Up / Authorization screen
![image](https://user-images.githubusercontent.com/89219486/162526934-faf251e6-955f-4a72-8701-d1cf3c237c78.png)

- [x] Hack#2 Add logout to CRUD screen
![image](https://user-images.githubusercontent.com/89219486/162527356-b6044cf8-f18d-47cc-83cc-599ee5e2e02a.png)

- [x] Hack#3 Add login_required to another portion of the project
Login required has been added to level1.html part of project. New login page, and forced to login before accessing page. 
![image](https://user-images.githubusercontent.com/89219486/162527488-daeae4f4-ac57-4339-9319-ef9dfbafbd43.png)

- [x] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.
Login is protecting level1.html file on page. Logout is also available on top of navbar. 
![image](https://user-images.githubusercontent.com/89219486/162527495-37f7face-97ec-4185-b3c1-24a47bf77915.png)

**Comment by somaditya1** [comment]
#Individual Score: 6/5
Team Score: 4/3
Individual Score: 2/2

Reviewed by Somaditya Singh

Score given 2/2. Create Task is completely and fully documented at this  
Video is detailed and present. The written responses have been completed. Code snippets and Replit is also documented. 
Account and Login hacks have also been successfully completed along with extra credit.

**Comment by nadirahaddach** [comment]
I agree with the grade given, a 6/5 would be correct for the work done. He has all the hacks done as well as the extra credit. Also, he has completed the college board Create Task requirements.

- Reviewed by Nadira Haddach
